package com.wowcraft.core.mod;

/**
 * Kinds of modifiers granted by talents, auras, gear and set bonuses.
 * MUL modifiers combine as product(1 + v); ADD modifiers are summed.
 */
public enum ModType {
    DAMAGE_DONE(Combine.MUL),
    HEALING_DONE(Combine.MUL),
    DAMAGE_TAKEN(Combine.MUL),
    HEALING_TAKEN(Combine.MUL),
    /** Flat crit chance percentage points. */
    CRIT_CHANCE(Combine.ADD),
    /** Bonus to the critical strike multiplier (0.2 = 200% -> 220%). */
    CRIT_DAMAGE(Combine.ADD),
    /** Haste percent points, multiplicative with rating haste. */
    HASTE(Combine.MUL),
    STAT_PCT(Combine.MUL),
    STAT_FLAT(Combine.ADD),
    MAX_HEALTH_PCT(Combine.MUL),
    MOVE_SPEED(Combine.MUL),
    /** Cooldown duration multiplier (-0.2 = 20% shorter). */
    COOLDOWN_PCT(Combine.MUL),
    /** Flat seconds added to a cooldown (negative = shorter). */
    COOLDOWN_FLAT(Combine.ADD),
    /** Cooldown recovery rate (+1.0 = recovers twice as fast). */
    COOLDOWN_RATE(Combine.ADD),
    COST_PCT(Combine.MUL),
    COST_FLAT(Combine.ADD),
    CAST_TIME_PCT(Combine.MUL),
    CHARGES(Combine.ADD),
    RANGE(Combine.ADD),
    DURATION_FLAT(Combine.ADD),
    DURATION_PCT(Combine.MUL),
    CAST_WHILE_MOVING(Combine.ADD),
    RESOURCE_REGEN_PCT(Combine.MUL),
    RESOURCE_MAX(Combine.ADD),
    /** Extra resource generated by abilities of the filter (flat). */
    RESOURCE_GEN_FLAT(Combine.ADD),
    THREAT_PCT(Combine.MUL),
    LEECH(Combine.ADD),
    AVOIDANCE(Combine.ADD),
    ABSORB_DONE(Combine.MUL),
    ARMOR_PCT(Combine.MUL),
    PET_DAMAGE(Combine.MUL),
    /** Immunity to a crowd-control category (ref = CcType name, or "ALL"). */
    CC_IMMUNE(Combine.ADD),
    /** Immunity to damage (ref = school name or "ALL"). */
    DAMAGE_IMMUNE(Combine.ADD),
    /** Unit cannot be targeted by enemies (e.g. Vanish, Ice Block style effects use DAMAGE_IMMUNE). */
    UNTARGETABLE(Combine.ADD),
    /** Talent: grants an ability (ref = ability id). */
    GRANT_ABILITY(Combine.ADD),
    /** Talent: replaces an ability on the action bar (ref = "from>to"). */
    REPLACE_ABILITY(Combine.ADD),
    /** Extra targets for chain / multi-target effects. */
    EXTRA_TARGETS(Combine.ADD),
    /** Multiplies periodic effect tick rate. */
    TICK_RATE(Combine.MUL),
    /** Increases radius of area effects (percent). */
    RADIUS_PCT(Combine.MUL),
    /** Bonus to damage against targets below 35% health (execute-style talents). */
    EXECUTE_DAMAGE(Combine.MUL),
    /** Damage dealt by this unit in PvP (player vs player). */
    PVP_DAMAGE(Combine.MUL);

    public enum Combine {ADD, MUL}

    public final Combine combine;

    ModType(Combine combine) {
        this.combine = combine;
    }
}
